let lorem = ["Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
             "Duis eget bibendum purus, vitae volutpat quam.",
             "Morbi quis facilisis metus.",
             "Phasellus finibus lorem non leo finibus dictum.",
             "Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae.",
             "Sed pretium, felis eu fermentum faucibus, diam velit scelerisque quam, vitae sagittis sapien massa sodales eros.",
             "Fusce eu lacinia massa.",
             "Proin vitae ex luctus, sodales arcu vel, gravida tellus.",
             "Fusce massa velit, hendrerit pharetra aliquam ut, porttitor nec nulla.",
             "Integer sodales id odio quis ultricies.",
             "Proin id sapien non mauris pellentesque fermentum.",
             "Etiam consequat sapien vitae justo tincidunt, malesuada ullamcorper dui fermentum.",
             "Curabitur semper velit quis erat tristique, sit amet fringilla metus elementum.",
             "Mauris accumsan at massa eget consectetur.",
             "Curabitur in est lectus.",
             "Mauris et pulvinar ex.",
             "Quisque nec pretium justo, id ullamcorper diam.",
             "Donec placerat nulla sit amet tempus lacinia.",
             "Nulla facilisi.",
             "Sed ut risus a neque convallis vestibulum sit amet vel leo.",
             "Aenean volutpat ornare placerat.",
             "Vestibulum purus mi, lacinia non risus vitae, consectetur venenatis lorem.",
             "Donec facilisis enim vitae sagittis aliquet.",
             "Nunc faucibus massa et mattis elementum.",
             "Aliquam tellus augue, varius a finibus nec, fringilla at dolor.",
             "Fusce dignissim erat sed vulputate vehicula.",
             "Morbi ultricies in ipsum quis rutrum.",
             "Duis aliquam laoreet nisl a vehicula.",
             "Morbi ante lorem, auctor porta egestas et, congue posuere erat.",
             "Curabitur sodales imperdiet libero, quis finibus sapien euismod non.",
             "Aliquam cursus ullamcorper congue.",
             "Phasellus faucibus sagittis efficitur.",
             "Nunc vulputate nisi a pharetra auctor.",
             "Quisque lectus urna, auctor eget pretium vitae, aliquet vel dolor.",
             "Donec vitae dolor ut augue rhoncus vulputate sed non arcu.",
             "In nec vulputate neque.",
             "Mauris varius augue et libero gravida tincidunt.",
             "Aliquam aliquet ut erat varius ullamcorper.",
             "Sed hendrerit cursus elit eget feugiat.",
             "Praesent neque ipsum, tincidunt eget tristique ac, eleifend non arcu.",
             "Nam tempus velit quis mollis mollis.",
             "Phasellus tristique posuere velit, et vulputate lacus hendrerit et.",
             "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
             "Sed est elit, feugiat sit amet neque et, semper volutpat eros.",
             "Morbi in aliquet urna.",
             "Sed facilisis, nulla ac accumsan convallis, ligula augue commodo leo, nec fermentum libero justo quis elit.",
             "Vivamus ornare neque aliquam dui hendrerit rhoncus.",
             "In lorem velit, pharetra non mauris id, mattis fermentum lacus.",
             "Nulla facilisi.",
             "Maecenas non dignissim ex, non pharetra augue.",
             "Donec ligula elit, varius eu gravida varius, fringilla vel arcu.",
             "Etiam mi neque, molestie vel arcu eu, ultrices placerat est.",
             "Etiam varius mi ut nibh commodo molestie.",
             "Vestibulum non nulla eu tortor suscipit vulputate aliquam et ipsum.",
             "Vivamus mi lorem, egestas eget nisl et, lobortis cursus diam.",
             "Praesent sit amet fringilla eros.",
             "In volutpat urna id nibh ullamcorper, faucibus volutpat odio ullamcorper.",
             "Pellentesque nibh dui, fermentum eget facilisis quis, lacinia sit amet est.",
             "Quisque vestibulum, justo sed lacinia condimentum, ex elit posuere justo, sit amet elementum metus urna ut nulla.",
             "Aenean convallis libero et sollicitudin rutrum.",
             "Praesent quis sollicitudin mi.",
             "Donec posuere rhoncus velit, in auctor nulla sagittis aliquam.",
             "In hac habitasse platea dictumst.",
             "Duis sit amet tellus dui.",
             "Maecenas ante sapien, ornare at urna in, faucibus vulputate diam.",
             "Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.",
             "Sed non fringilla sapien.",
             "In consequat, mi eu feugiat varius, dolor nunc semper urna, vitae aliquet diam lorem sed sem.",
             "Pellentesque ut tellus lobortis, mattis eros ac, eleifend elit.",
             "Aenean quis risus tristique, viverra urna et, sagittis sem.",
             "Vivamus ullamcorper laoreet felis, ut accumsan dolor aliquet quis."];